#!/usr/bin/env python

# based off the waf file from the official LV2 examples,
# with quite a few cxx compiler hacks to get it to compile
# code in C++ as well as C

from waflib.extras import autowaf as autowaf
import re

# Variables for 'waf dist'
APPNAME = 'amp-osc.lv2'
VERSION = '1.0.0'

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    opt.load('compiler_c compiler_cxx')
    autowaf.set_options(opt)

def configure(conf):
    conf.load('compiler_c compiler_cxx')
    autowaf.configure(conf)
    autowaf.set_c99_mode(conf)
    autowaf.display_header('AmpOsc Configuration')

    if not autowaf.is_child():
        autowaf.check_pkg(conf, 'lv2', uselib_store='LV2')

    conf.check(features='cxx cxxshlib', lib='m', uselib_store='M', mandatory=False)

    autowaf.display_msg(conf, 'LV2 bundle directory', conf.env.LV2DIR)
    print('')

def build(bld):
    bundle = 'amp-osc.lv2'

    # Make a pattern for shared objects without the 'lib' prefix
    module_pat = re.sub('^lib', '', bld.env.cxxshlib_PATTERN)
    module_ext = module_pat[module_pat.rfind('.'):]

    # Build manifest.ttl by substitution (for portable lib extension)
    bld(features     = 'subst',
        source       = 'manifest.ttl.in',
        target       = '%s/%s' % (bundle, 'manifest.ttl'),
        install_path = '${LV2DIR}/%s' % bundle,
        LIB_EXT      = module_ext)

    # Copy other data files to build bundle (build/eg-amp.lv2)
    for i in ['amp-osc.ttl']:
        bld(features     = 'subst',
            is_copy      = True,
            source       = i,
            target       = '%s/%s' % (bundle, i),
            install_path = '${LV2DIR}/%s' % bundle)

    # Build plugin library
    obj = bld(features     = 'cxx cxxshlib',
              source       = 'amp-osc.cpp',
              name         = 'amp-osc',
              target       = '%s/amp-osc' % bundle,
              install_path = '${LV2DIR}/%s' % bundle,
              uselib       = 'M LV2',
              #includes     = includes
              )
    obj.env.cxxshlib_PATTERN = module_pat
